#include "nwep_napi.h"

#define SET_INT(name, val)                                                     \
  do {                                                                         \
    napi_value _v;                                                             \
    napi_create_int32(env, (val), &_v);                                        \
    napi_set_named_property(env, exports, (name), _v);                         \
  } while (0)

#define SET_UINT(name, val)                                                    \
  do {                                                                         \
    napi_value _v;                                                             \
    napi_create_uint32(env, (uint32_t)(val), &_v);                             \
    napi_set_named_property(env, exports, (name), _v);                         \
  } while (0)

#define SET_UINT64(name, val)                                                  \
  do {                                                                         \
    napi_value _v;                                                             \
    napi_create_bigint_uint64(env, (uint64_t)(val), &_v);                      \
    napi_set_named_property(env, exports, (name), _v);                         \
  } while (0)

#define SET_STR(name, val)                                                     \
  do {                                                                         \
    napi_value _v;                                                             \
    napi_create_string_utf8(env, (val), NAPI_AUTO_LENGTH, &_v);                \
    napi_set_named_property(env, exports, (name), _v);                         \
  } while (0)

napi_value nwep_napi_init_constants(napi_env env, napi_value exports) {
  SET_UINT64("NANOSECONDS", NWEP_NANOSECONDS);
  SET_UINT64("MICROSECONDS", NWEP_MICROSECONDS);
  SET_UINT64("MILLISECONDS", NWEP_MILLISECONDS);
  SET_UINT64("SECONDS", NWEP_SECONDS);

  SET_STR("PROTO_VER", NWEP_PROTO_VER);
  SET_STR("ALPN", NWEP_ALPN);
  SET_UINT("ALPN_LEN", NWEP_ALPN_LEN);
  SET_UINT("DEFAULT_PORT", NWEP_DEFAULT_PORT);

  SET_UINT("DEFAULT_MAX_MESSAGE_SIZE", NWEP_DEFAULT_MAX_MESSAGE_SIZE);
  SET_UINT("MAX_HEADERS", NWEP_MAX_HEADERS);
  SET_UINT("MAX_HEADER_SIZE", NWEP_MAX_HEADER_SIZE);
  SET_UINT("DEFAULT_MAX_STREAMS", NWEP_DEFAULT_MAX_STREAMS);
  SET_UINT64("DEFAULT_TIMEOUT", NWEP_DEFAULT_TIMEOUT);

  SET_UINT("ED25519_PUBKEY_LEN", NWEP_ED25519_PUBKEY_LEN);
  SET_UINT("ED25519_PRIVKEY_LEN", NWEP_ED25519_PRIVKEY_LEN);
  SET_UINT("ED25519_SIG_LEN", NWEP_ED25519_SIG_LEN);
  SET_UINT("NODEID_LEN", NWEP_NODEID_LEN);
  SET_UINT("CHALLENGE_LEN", NWEP_CHALLENGE_LEN);
  SET_UINT("REQUEST_ID_LEN", NWEP_REQUEST_ID_LEN);
  SET_UINT("TRACE_ID_LEN", NWEP_TRACE_ID_LEN);

  SET_UINT("MSG_REQUEST", NWEP_MSG_REQUEST);
  SET_UINT("MSG_RESPONSE", NWEP_MSG_RESPONSE);
  SET_UINT("MSG_STREAM", NWEP_MSG_STREAM);
  SET_UINT("MSG_NOTIFY", NWEP_MSG_NOTIFY);

  SET_STR("METHOD_READ", NWEP_METHOD_READ);
  SET_STR("METHOD_WRITE", NWEP_METHOD_WRITE);
  SET_STR("METHOD_UPDATE", NWEP_METHOD_UPDATE);
  SET_STR("METHOD_DELETE", NWEP_METHOD_DELETE);
  SET_STR("METHOD_CONNECT", NWEP_METHOD_CONNECT);
  SET_STR("METHOD_AUTHENTICATE", NWEP_METHOD_AUTHENTICATE);
  SET_STR("METHOD_HEARTBEAT", NWEP_METHOD_HEARTBEAT);

  SET_STR("STATUS_OK", NWEP_STATUS_OK);
  SET_STR("STATUS_CREATED", NWEP_STATUS_CREATED);
  SET_STR("STATUS_ACCEPTED", NWEP_STATUS_ACCEPTED);
  SET_STR("STATUS_NO_CONTENT", NWEP_STATUS_NO_CONTENT);
  SET_STR("STATUS_BAD_REQUEST", NWEP_STATUS_BAD_REQUEST);
  SET_STR("STATUS_UNAUTHORIZED", NWEP_STATUS_UNAUTHORIZED);
  SET_STR("STATUS_FORBIDDEN", NWEP_STATUS_FORBIDDEN);
  SET_STR("STATUS_NOT_FOUND", NWEP_STATUS_NOT_FOUND);
  SET_STR("STATUS_CONFLICT", NWEP_STATUS_CONFLICT);
  SET_STR("STATUS_RATE_LIMITED", NWEP_STATUS_RATE_LIMITED);
  SET_STR("STATUS_INTERNAL_ERROR", NWEP_STATUS_INTERNAL_ERROR);
  SET_STR("STATUS_UNAVAILABLE", NWEP_STATUS_UNAVAILABLE);

  SET_INT("ERR_CONFIG_FILE_NOT_FOUND", NWEP_ERR_CONFIG_FILE_NOT_FOUND);
  SET_INT("ERR_CONFIG_PARSE_ERROR", NWEP_ERR_CONFIG_PARSE_ERROR);
  SET_INT("ERR_CONFIG_INVALID_VALUE", NWEP_ERR_CONFIG_INVALID_VALUE);
  SET_INT("ERR_CONFIG_MISSING_REQUIRED", NWEP_ERR_CONFIG_MISSING_REQUIRED);
  SET_INT("ERR_CONFIG_VALIDATION_FAILED", NWEP_ERR_CONFIG_VALIDATION_FAILED);

  SET_INT("ERR_NETWORK_CONN_FAILED", NWEP_ERR_NETWORK_CONN_FAILED);
  SET_INT("ERR_NETWORK_CONN_CLOSED", NWEP_ERR_NETWORK_CONN_CLOSED);
  SET_INT("ERR_NETWORK_TIMEOUT", NWEP_ERR_NETWORK_TIMEOUT);
  SET_INT("ERR_NETWORK_ADDR_IN_USE", NWEP_ERR_NETWORK_ADDR_IN_USE);
  SET_INT("ERR_NETWORK_ADDR_INVALID", NWEP_ERR_NETWORK_ADDR_INVALID);
  SET_INT("ERR_NETWORK_SOCKET", NWEP_ERR_NETWORK_SOCKET);
  SET_INT("ERR_NETWORK_TLS", NWEP_ERR_NETWORK_TLS);
  SET_INT("ERR_NETWORK_QUIC", NWEP_ERR_NETWORK_QUIC);
  SET_INT("ERR_NETWORK_NO_SERVERS", NWEP_ERR_NETWORK_NO_SERVERS);

  SET_INT("ERR_CRYPTO_KEY_GEN_FAILED", NWEP_ERR_CRYPTO_KEY_GEN_FAILED);
  SET_INT("ERR_CRYPTO_SIGN_FAILED", NWEP_ERR_CRYPTO_SIGN_FAILED);
  SET_INT("ERR_CRYPTO_VERIFY_FAILED", NWEP_ERR_CRYPTO_VERIFY_FAILED);
  SET_INT("ERR_CRYPTO_HASH_FAILED", NWEP_ERR_CRYPTO_HASH_FAILED);
  SET_INT("ERR_CRYPTO_INVALID_KEY", NWEP_ERR_CRYPTO_INVALID_KEY);
  SET_INT("ERR_CRYPTO_INVALID_SIG", NWEP_ERR_CRYPTO_INVALID_SIG);
  SET_INT("ERR_CRYPTO_ENCRYPT_FAILED", NWEP_ERR_CRYPTO_ENCRYPT_FAILED);
  SET_INT("ERR_CRYPTO_DECRYPT_FAILED", NWEP_ERR_CRYPTO_DECRYPT_FAILED);
  SET_INT("ERR_CRYPTO_KEY_LOAD_FAILED", NWEP_ERR_CRYPTO_KEY_LOAD_FAILED);
  SET_INT("ERR_CRYPTO_KEY_SAVE_FAILED", NWEP_ERR_CRYPTO_KEY_SAVE_FAILED);
  SET_INT("ERR_CRYPTO_CERT_ERROR", NWEP_ERR_CRYPTO_CERT_ERROR);
  SET_INT("ERR_CRYPTO_PUBKEY_MISMATCH", NWEP_ERR_CRYPTO_PUBKEY_MISMATCH);
  SET_INT("ERR_CRYPTO_NODEID_MISMATCH", NWEP_ERR_CRYPTO_NODEID_MISMATCH);
  SET_INT("ERR_CRYPTO_CHALLENGE_FAILED", NWEP_ERR_CRYPTO_CHALLENGE_FAILED);
  SET_INT("ERR_CRYPTO_SERVER_SIG_INVALID",
          NWEP_ERR_CRYPTO_SERVER_SIG_INVALID);
  SET_INT("ERR_CRYPTO_CLIENT_SIG_INVALID",
          NWEP_ERR_CRYPTO_CLIENT_SIG_INVALID);
  SET_INT("ERR_CRYPTO_AUTH_TIMEOUT", NWEP_ERR_CRYPTO_AUTH_TIMEOUT);

  SET_INT("ERR_PROTO_INVALID_MESSAGE", NWEP_ERR_PROTO_INVALID_MESSAGE);
  SET_INT("ERR_PROTO_INVALID_METHOD", NWEP_ERR_PROTO_INVALID_METHOD);
  SET_INT("ERR_PROTO_INVALID_HEADER", NWEP_ERR_PROTO_INVALID_HEADER);
  SET_INT("ERR_PROTO_MSG_TOO_LARGE", NWEP_ERR_PROTO_MSG_TOO_LARGE);
  SET_INT("ERR_PROTO_STREAM_ERROR", NWEP_ERR_PROTO_STREAM_ERROR);
  SET_INT("ERR_PROTO_INVALID_STATUS", NWEP_ERR_PROTO_INVALID_STATUS);
  SET_INT("ERR_PROTO_CONNECT_REQUIRED", NWEP_ERR_PROTO_CONNECT_REQUIRED);
  SET_INT("ERR_PROTO_TOO_MANY_HEADERS", NWEP_ERR_PROTO_TOO_MANY_HEADERS);
  SET_INT("ERR_PROTO_HEADER_TOO_LARGE", NWEP_ERR_PROTO_HEADER_TOO_LARGE);
  SET_INT("ERR_PROTO_0RTT_REJECTED", NWEP_ERR_PROTO_0RTT_REJECTED);
  SET_INT("ERR_PROTO_MISSING_HEADER", NWEP_ERR_PROTO_MISSING_HEADER);
  SET_INT("ERR_PROTO_ROLE_MISMATCH", NWEP_ERR_PROTO_ROLE_MISMATCH);
  SET_INT("ERR_PROTO_UNAUTHORIZED", NWEP_ERR_PROTO_UNAUTHORIZED);
  SET_INT("ERR_PROTO_PATH_NOT_FOUND", NWEP_ERR_PROTO_PATH_NOT_FOUND);
  SET_INT("ERR_PROTO_VERSION_MISMATCH", NWEP_ERR_PROTO_VERSION_MISMATCH);

  SET_INT("ERR_IDENTITY_INVALID_NODEID", NWEP_ERR_IDENTITY_INVALID_NODEID);
  SET_INT("ERR_IDENTITY_INVALID_ADDR", NWEP_ERR_IDENTITY_INVALID_ADDR);
  SET_INT("ERR_IDENTITY_AUTH_FAILED", NWEP_ERR_IDENTITY_AUTH_FAILED);
  SET_INT("ERR_IDENTITY_CHALLENGE_EXPIRED",
          NWEP_ERR_IDENTITY_CHALLENGE_EXPIRED);
  SET_INT("ERR_IDENTITY_NO_RECOVERY", NWEP_ERR_IDENTITY_NO_RECOVERY);
  SET_INT("ERR_IDENTITY_RECOVERY_MISMATCH",
          NWEP_ERR_IDENTITY_RECOVERY_MISMATCH);
  SET_INT("ERR_IDENTITY_INVALID_SHARE", NWEP_ERR_IDENTITY_INVALID_SHARE);
  SET_INT("ERR_IDENTITY_SHARE_COMBINE", NWEP_ERR_IDENTITY_SHARE_COMBINE);
  SET_INT("ERR_IDENTITY_INVALID_THRESHOLD",
          NWEP_ERR_IDENTITY_INVALID_THRESHOLD);
  SET_INT("ERR_IDENTITY_ROTATION_IN_PROGRESS",
          NWEP_ERR_IDENTITY_ROTATION_IN_PROGRESS);
  SET_INT("ERR_IDENTITY_KEY_MISMATCH", NWEP_ERR_IDENTITY_KEY_MISMATCH);
  SET_INT("ERR_IDENTITY_REVOKED", NWEP_ERR_IDENTITY_REVOKED);

  SET_INT("ERR_STORAGE_FILE_NOT_FOUND", NWEP_ERR_STORAGE_FILE_NOT_FOUND);
  SET_INT("ERR_STORAGE_READ_ERROR", NWEP_ERR_STORAGE_READ_ERROR);
  SET_INT("ERR_STORAGE_WRITE_ERROR", NWEP_ERR_STORAGE_WRITE_ERROR);
  SET_INT("ERR_STORAGE_PERMISSION", NWEP_ERR_STORAGE_PERMISSION);
  SET_INT("ERR_STORAGE_DISK_FULL", NWEP_ERR_STORAGE_DISK_FULL);
  SET_INT("ERR_STORAGE_KEY_NOT_FOUND", NWEP_ERR_STORAGE_KEY_NOT_FOUND);
  SET_INT("ERR_STORAGE_INDEX_OUT_OF_RANGE",
          NWEP_ERR_STORAGE_INDEX_OUT_OF_RANGE);
  SET_INT("ERR_STORAGE_CORRUPTED", NWEP_ERR_STORAGE_CORRUPTED);

  SET_INT("ERR_TRUST_PARSE_ERROR", NWEP_ERR_TRUST_PARSE_ERROR);
  SET_INT("ERR_TRUST_INVALID_ENTRY", NWEP_ERR_TRUST_INVALID_ENTRY);
  SET_INT("ERR_TRUST_INVALID_SIG", NWEP_ERR_TRUST_INVALID_SIG);
  SET_INT("ERR_TRUST_QUORUM_NOT_REACHED", NWEP_ERR_TRUST_QUORUM_NOT_REACHED);
  SET_INT("ERR_TRUST_INVALID_PROOF", NWEP_ERR_TRUST_INVALID_PROOF);
  SET_INT("ERR_TRUST_ENTRY_NOT_FOUND", NWEP_ERR_TRUST_ENTRY_NOT_FOUND);
  SET_INT("ERR_TRUST_CHECKPOINT_STALE", NWEP_ERR_TRUST_CHECKPOINT_STALE);
  SET_INT("ERR_TRUST_ANCHOR_UNKNOWN", NWEP_ERR_TRUST_ANCHOR_UNKNOWN);
  SET_INT("ERR_TRUST_DUPLICATE_BINDING", NWEP_ERR_TRUST_DUPLICATE_BINDING);
  SET_INT("ERR_TRUST_NODE_NOT_FOUND", NWEP_ERR_TRUST_NODE_NOT_FOUND);
  SET_INT("ERR_TRUST_ALREADY_REVOKED", NWEP_ERR_TRUST_ALREADY_REVOKED);
  SET_INT("ERR_TRUST_INVALID_AUTH", NWEP_ERR_TRUST_INVALID_AUTH);
  SET_INT("ERR_TRUST_UNAUTHORIZED", NWEP_ERR_TRUST_UNAUTHORIZED);
  SET_INT("ERR_TRUST_TYPE_NOT_ALLOWED", NWEP_ERR_TRUST_TYPE_NOT_ALLOWED);
  SET_INT("ERR_TRUST_KEY_MISMATCH", NWEP_ERR_TRUST_KEY_MISMATCH);
  SET_INT("ERR_TRUST_STORAGE", NWEP_ERR_TRUST_STORAGE);
  SET_INT("ERR_TRUST_LOG_CORRUPTED", NWEP_ERR_TRUST_LOG_CORRUPTED);
  SET_INT("ERR_TRUST_EQUIVOCATION", NWEP_ERR_TRUST_EQUIVOCATION);

  SET_INT("ERR_INTERNAL_UNKNOWN", NWEP_ERR_INTERNAL_UNKNOWN);
  SET_INT("ERR_INTERNAL_NOT_IMPLEMENTED", NWEP_ERR_INTERNAL_NOT_IMPLEMENTED);
  SET_INT("ERR_INTERNAL_INVALID_STATE", NWEP_ERR_INTERNAL_INVALID_STATE);
  SET_INT("ERR_INTERNAL_NULL_PTR", NWEP_ERR_INTERNAL_NULL_PTR);
  SET_INT("ERR_INTERNAL_NOMEM", NWEP_ERR_INTERNAL_NOMEM);
  SET_INT("ERR_INTERNAL_INVALID_ARG", NWEP_ERR_INTERNAL_INVALID_ARG);
  SET_INT("ERR_INTERNAL_CALLBACK_FAILURE",
          NWEP_ERR_INTERNAL_CALLBACK_FAILURE);
  SET_INT("ERR_INTERNAL_NOBUF", NWEP_ERR_INTERNAL_NOBUF);

  SET_UINT("ERR_FATAL_THRESHOLD", NWEP_ERR_FATAL_THRESHOLD);
  SET_UINT("ERR_CONTEXT_MAX", NWEP_ERR_CONTEXT_MAX);

  SET_UINT("FRAME_HEADER_SIZE", NWEP_FRAME_HEADER_SIZE);
  SET_UINT("MSG_TYPE_SIZE", NWEP_MSG_TYPE_SIZE);

  SET_STR("HDR_METHOD", NWEP_HDR_METHOD);
  SET_STR("HDR_PATH", NWEP_HDR_PATH);
  SET_STR("HDR_VERSION", NWEP_HDR_VERSION);
  SET_STR("HDR_STATUS", NWEP_HDR_STATUS);
  SET_STR("HDR_REQUEST_ID", NWEP_HDR_REQUEST_ID);
  SET_STR("HDR_CLIENT_ID", NWEP_HDR_CLIENT_ID);
  SET_STR("HDR_SERVER_ID", NWEP_HDR_SERVER_ID);
  SET_STR("HDR_CHALLENGE", NWEP_HDR_CHALLENGE);
  SET_STR("HDR_CHALLENGE_RESPONSE", NWEP_HDR_CHALLENGE_RESPONSE);
  SET_STR("HDR_SERVER_CHALLENGE", NWEP_HDR_SERVER_CHALLENGE);
  SET_STR("HDR_AUTH_RESPONSE", NWEP_HDR_AUTH_RESPONSE);
  SET_STR("HDR_MAX_STREAMS", NWEP_HDR_MAX_STREAMS);
  SET_STR("HDR_MAX_MESSAGE_SIZE", NWEP_HDR_MAX_MESSAGE_SIZE);
  SET_STR("HDR_COMPRESSION", NWEP_HDR_COMPRESSION);
  SET_STR("HDR_ROLES", NWEP_HDR_ROLES);
  SET_STR("HDR_TRANSCRIPT_SIG", NWEP_HDR_TRANSCRIPT_SIG);
  SET_STR("HDR_STATUS_DETAILS", NWEP_HDR_STATUS_DETAILS);
  SET_STR("HDR_RETRY_AFTER", NWEP_HDR_RETRY_AFTER);
  SET_STR("HDR_TRACE_ID", NWEP_HDR_TRACE_ID);
  SET_STR("HDR_EVENT", NWEP_HDR_EVENT);
  SET_STR("HDR_NOTIFY_ID", NWEP_HDR_NOTIFY_ID);

  SET_UINT("BASE58_ADDR_LEN", NWEP_BASE58_ADDR_LEN);

  SET_UINT("URL_MAX_LEN", NWEP_URL_MAX_LEN);

  SET_UINT("SHAMIR_MAX_SHARES", NWEP_SHAMIR_MAX_SHARES);
  SET_UINT("SHAMIR_MIN_THRESHOLD", NWEP_SHAMIR_MIN_THRESHOLD);

  SET_UINT("KEY_OVERLAP_SECONDS", NWEP_KEY_OVERLAP_SECONDS);
  SET_UINT("MAX_ACTIVE_KEYS", NWEP_MAX_ACTIVE_KEYS);

  SET_UINT("LOG_ENTRY_MAX_SIZE", NWEP_LOG_ENTRY_MAX_SIZE);
  SET_UINT("MERKLE_PROOF_MAX_DEPTH", NWEP_MERKLE_PROOF_MAX_DEPTH);
  SET_UINT("LOG_ENTRY_KEY_BINDING", NWEP_LOG_ENTRY_KEY_BINDING);
  SET_UINT("LOG_ENTRY_KEY_ROTATION", NWEP_LOG_ENTRY_KEY_ROTATION);
  SET_UINT("LOG_ENTRY_REVOCATION", NWEP_LOG_ENTRY_REVOCATION);
  SET_UINT("LOG_ENTRY_ANCHOR_CHANGE", NWEP_LOG_ENTRY_ANCHOR_CHANGE);

  SET_UINT("BLS_PUBKEY_LEN", NWEP_BLS_PUBKEY_LEN);
  SET_UINT("BLS_PRIVKEY_LEN", NWEP_BLS_PRIVKEY_LEN);
  SET_UINT("BLS_SIG_LEN", NWEP_BLS_SIG_LEN);
  SET_STR("CHECKPOINT_DST", NWEP_CHECKPOINT_DST);
  SET_UINT("DEFAULT_ANCHOR_THRESHOLD", NWEP_DEFAULT_ANCHOR_THRESHOLD);
  SET_UINT("MAX_ANCHORS", NWEP_MAX_ANCHORS);
  SET_UINT64("DEFAULT_EPOCH_INTERVAL", NWEP_DEFAULT_EPOCH_INTERVAL);

  SET_UINT64("STALENESS_WARNING_NS", NWEP_STALENESS_WARNING_NS);
  SET_UINT64("STALENESS_REJECT_NS", NWEP_STALENESS_REJECT_NS);
  SET_UINT64("IDENTITY_CACHE_TTL", NWEP_IDENTITY_CACHE_TTL);
  SET_UINT("MAX_CHECKPOINTS", NWEP_MAX_CHECKPOINTS);
  SET_UINT("STALENESS_FRESH", NWEP_STALENESS_FRESH);
  SET_UINT("STALENESS_WARNING", NWEP_STALENESS_WARNING);
  SET_UINT("STALENESS_REJECT", NWEP_STALENESS_REJECT);

  SET_UINT("ROLE_REGULAR", NWEP_ROLE_REGULAR);
  SET_UINT("ROLE_LOG_SERVER", NWEP_ROLE_LOG_SERVER);
  SET_UINT("ROLE_ANCHOR", NWEP_ROLE_ANCHOR);
  SET_STR("ROLE_STR_REGULAR", NWEP_ROLE_STR_REGULAR);
  SET_STR("ROLE_STR_LOG_SERVER", NWEP_ROLE_STR_LOG_SERVER);
  SET_STR("ROLE_STR_ANCHOR", NWEP_ROLE_STR_ANCHOR);

  SET_UINT("CACHE_DEFAULT_CAPACITY", NWEP_CACHE_DEFAULT_CAPACITY);
  SET_UINT64("CACHE_DEFAULT_TTL_NS", NWEP_CACHE_DEFAULT_TTL_NS);
  SET_UINT("POOL_MAX_SERVERS", NWEP_POOL_MAX_SERVERS);
  SET_UINT("POOL_HEALTH_CHECK_FAILURES", NWEP_POOL_HEALTH_CHECK_FAILURES);
  SET_UINT("POOL_ROUND_ROBIN", NWEP_POOL_ROUND_ROBIN);
  SET_UINT("POOL_RANDOM", NWEP_POOL_RANDOM);
  SET_UINT("SERVER_HEALTHY", NWEP_SERVER_HEALTHY);
  SET_UINT("SERVER_UNHEALTHY", NWEP_SERVER_UNHEALTHY);

  SET_UINT("NOTIFY_ID_LEN", NWEP_NOTIFY_ID_LEN);

  SET_UINT("CLIENT_STATE_INITIAL", NWEP_CLIENT_STATE_INITIAL);
  SET_UINT("CLIENT_STATE_TLS_HANDSHAKE", NWEP_CLIENT_STATE_TLS_HANDSHAKE);
  SET_UINT("CLIENT_STATE_SEND_CONNECT", NWEP_CLIENT_STATE_SEND_CONNECT);
  SET_UINT("CLIENT_STATE_WAIT_CONNECT_RESP",
           NWEP_CLIENT_STATE_WAIT_CONNECT_RESP);
  SET_UINT("CLIENT_STATE_SEND_AUTHENTICATE",
           NWEP_CLIENT_STATE_SEND_AUTHENTICATE);
  SET_UINT("CLIENT_STATE_WAIT_AUTH_RESP", NWEP_CLIENT_STATE_WAIT_AUTH_RESP);
  SET_UINT("CLIENT_STATE_CONNECTED", NWEP_CLIENT_STATE_CONNECTED);
  SET_UINT("CLIENT_STATE_ERROR", NWEP_CLIENT_STATE_ERROR);

  SET_UINT("SERVER_STATE_INITIAL", NWEP_SERVER_STATE_INITIAL);
  SET_UINT("SERVER_STATE_TLS_HANDSHAKE", NWEP_SERVER_STATE_TLS_HANDSHAKE);
  SET_UINT("SERVER_STATE_AWAITING_CONNECT",
           NWEP_SERVER_STATE_AWAITING_CONNECT);
  SET_UINT("SERVER_STATE_AWAITING_CLIENT_AUTH",
           NWEP_SERVER_STATE_AWAITING_CLIENT_AUTH);
  SET_UINT("SERVER_STATE_CONNECTED", NWEP_SERVER_STATE_CONNECTED);
  SET_UINT("SERVER_STATE_ERROR", NWEP_SERVER_STATE_ERROR);

  SET_UINT("LOG_TRACE", NWEP_LOG_TRACE);
  SET_UINT("LOG_DEBUG", NWEP_LOG_DEBUG);
  SET_UINT("LOG_INFO", NWEP_LOG_INFO);
  SET_UINT("LOG_WARN", NWEP_LOG_WARN);
  SET_UINT("LOG_ERROR", NWEP_LOG_ERROR);

  SET_UINT("ERR_CAT_NONE", NWEP_ERR_CAT_NONE);
  SET_UINT("ERR_CAT_CONFIG", NWEP_ERR_CAT_CONFIG);
  SET_UINT("ERR_CAT_NETWORK", NWEP_ERR_CAT_NETWORK);
  SET_UINT("ERR_CAT_CRYPTO", NWEP_ERR_CAT_CRYPTO);
  SET_UINT("ERR_CAT_PROTOCOL", NWEP_ERR_CAT_PROTOCOL);
  SET_UINT("ERR_CAT_IDENTITY", NWEP_ERR_CAT_IDENTITY);
  SET_UINT("ERR_CAT_STORAGE", NWEP_ERR_CAT_STORAGE);
  SET_UINT("ERR_CAT_TRUST", NWEP_ERR_CAT_TRUST);
  SET_UINT("ERR_CAT_INTERNAL", NWEP_ERR_CAT_INTERNAL);

  return exports;
}
